services:
    mongodb:
        image: mongo:7
        container_name: local-mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: mydb
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express:1
        container_name: local-mongo-express
        restart: unless-stopped
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_BASICAUTH: 'false'
        depends_on:
            - mongodb

volumes:
    mongo_data:
