FROM node:lts-alpine AS base

WORKDIR /app

COPY package*.json .

RUN npm i

COPY . .

FROM  base AS dev
CMD [ "npm", "run", "start:dev" ]

FROM base AS build
RUN npm run build
RUN npx prisma db push
RUN npx prisma generate

FROM base AS production
CMD [ "npm", "run", "start:prod" ]

