version: '3.9'
services:
    backend:
        build:
            context: .
            target: dev
        container_name: chloe-backend
        ports:
            - '8000:8000'
        environment:
            - NODE_ENV=development
            - PORT=8000
            - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
            - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
            - LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
            - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
        volumes:
            # Monter le code source pour le hot-reload
            - ./:/app
            - ./nest-cli.json:/app/nest-cli.json
            # Volume anonyme pour node_modules (performance)
            - node_modules_cache:/app/node_modules
        restart: unless-stopped
        networks:
            - app-network
volumes:
    node_modules_cache:

networks:
    app-network:
        driver: bridge
