version: '3.9'
services:
    backend:
        build:
            context: .
            target: prod
        container_name: chloe-backend
        ports:
            - '8000:8000'
        environment:
            - PORT=8000
            - MONGO_URI=mongodb://mongodb:27017/chloe
        depends_on:
            - mongodb
        volumes:
            - ./:/app
            - /app/node_modules
    mongodb:
        image: mongo:7
        container_name: local-mongo
        command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']
        ports: ['27017:27017']
        restart: unless-stopped
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express:1
        container_name: local-mongo-express
        restart: unless-stopped
        ports: ['8081:8081']
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH: 'false'
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
        depends_on:
            - mongodb

volumes:
    mongo_data:
